# Generated by Django 5.2 on 2025-04-29 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_customuser_permissions_alter_listing_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='permissions',
        ),
    ]
