# Generated by Django 5.2 on 2025-05-01 21:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_customuser_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used_good', 'Used - Good'), ('used_fair', 'Used - Fair')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
