# Generated by Django 5.2 on 2025-04-22 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_campuslocation_universities'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.universities'),
        ),
    ]
