# Generated by Django 5.2 on 2025-05-02 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_conversation_message_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
