# Generated by Django 5.2 on 2025-05-02 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_created_at_message_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
